PR dev branch Bubble Sort program
ad9311/ruby_bubble_sort pull request #1
Opened 2021-04-27 21:08 UTC by ad9311

# Advanced Building Blocks - Bubble Sort
## Greetings! 👋🏽 

In this PR we present our Bubble Sort program that contains two methods as required. 
We have decided to use an integer array to showcase the results.  

This program was created by @fortuneonyeka and @ad9311

2021-04-27 22:07 UTC, Dipeshtwis requested changes
# Status:  ♻️ Changes Required ♻️
 Hi @ad9311 and @fortuneonyeka

**You've really hit all the requirements in one shot. Well done.** Here're the major highlights of this PR:
- bubble_sort method implements the bubble sort algorithm.
- bubble_sort_by method is implemented and working

**However, in order to approve, we have to work a little bit more. Please check my comments below and fix them as appropriate.**

## For Approval

- [x] Do not commit debugging instructions in your code. Remove every other code that is not required in your project. Please see the in-line comments.
- [x] In your readme file, instead of using a statement to guide you can show with your code. Think about a person who is not from a technical background.


## Please make the required changes and submit another review request when you are done.

(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk) | [Twitter](https://twitter.com/97deepeshkumar)

2021-04-27 22:07 UTC, Dipeshtwis commented on README.md
> +If you want to check the source code out clone the repo. To know more about cloning and how git works check this page [Getting Started With Git](https://docs.github.com/en/github/getting-started-with
You can mention the command to clone and how to enter it into your folder before running your ruby file or rubocop.
```
$ git clone your-link.git
$ cd ruby_bubble_sort
```

2021-04-27 22:07 UTC, Dipeshtwis commented on bubble_sort.rb
> +puts bubble_sort(numbers)
Remove this line of code from your project.

2021-04-28 02:14 UTC, ad9311 commented
#### UPDATE

The following changes were made as per requested:
- Remove from bubble_sort.rb unnecessary piece of code.
- Update README.md to have more helpful content.

2021-04-28 02:26 UTC, mke2111 approved these changes
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey Happy Coders, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. The readme file is clear and concise
    2. The linter checks run just fine
    3. The sorting methods do exactly just that.

### **_Room for Improvement_** 🤪 

    1. You may choose to remove the line `git checkout dev` from the getting started section of the readme file. Your app will mostly live in develop/main branch.

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-04-28 02:33 UTC, merged